// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package twittermodule.proxies;

/**
 * Represents a Twitter tweet.
 */
public class Tweet
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject tweetMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TwitterModule.Tweet";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TweetId("TweetId"),
		CreatedAt("CreatedAt"),
		TextPlain("TextPlain"),
		TextFormatted("TextFormatted"),
		Source("Source"),
		RetweetCount("RetweetCount"),
		FavoriteCount("FavoriteCount"),
		TweetUser("TwitterModule.TweetUser");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Tweet(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TwitterModule.Tweet"));
	}

	protected Tweet(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject tweetMendixObject)
	{
		if (tweetMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TwitterModule.Tweet", tweetMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TwitterModule.Tweet");

		this.tweetMendixObject = tweetMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Tweet.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static twittermodule.proxies.Tweet initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return twittermodule.proxies.Tweet.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static twittermodule.proxies.Tweet initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new twittermodule.proxies.Tweet(context, mendixObject);
	}

	public static twittermodule.proxies.Tweet load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return twittermodule.proxies.Tweet.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of TweetId
	 */
	public final java.lang.Long getTweetId()
	{
		return getTweetId(getContext());
	}

	/**
	 * @param context
	 * @return value of TweetId
	 */
	public final java.lang.Long getTweetId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.TweetId.toString());
	}

	/**
	 * Set value of TweetId
	 * @param tweetid
	 */
	public final void setTweetId(java.lang.Long tweetid)
	{
		setTweetId(getContext(), tweetid);
	}

	/**
	 * Set value of TweetId
	 * @param context
	 * @param tweetid
	 */
	public final void setTweetId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long tweetid)
	{
		getMendixObject().setValue(context, MemberNames.TweetId.toString(), tweetid);
	}

	/**
	 * @return value of CreatedAt
	 */
	public final java.util.Date getCreatedAt()
	{
		return getCreatedAt(getContext());
	}

	/**
	 * @param context
	 * @return value of CreatedAt
	 */
	public final java.util.Date getCreatedAt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.CreatedAt.toString());
	}

	/**
	 * Set value of CreatedAt
	 * @param createdat
	 */
	public final void setCreatedAt(java.util.Date createdat)
	{
		setCreatedAt(getContext(), createdat);
	}

	/**
	 * Set value of CreatedAt
	 * @param context
	 * @param createdat
	 */
	public final void setCreatedAt(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date createdat)
	{
		getMendixObject().setValue(context, MemberNames.CreatedAt.toString(), createdat);
	}

	/**
	 * @return value of TextPlain
	 */
	public final java.lang.String getTextPlain()
	{
		return getTextPlain(getContext());
	}

	/**
	 * @param context
	 * @return value of TextPlain
	 */
	public final java.lang.String getTextPlain(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TextPlain.toString());
	}

	/**
	 * Set value of TextPlain
	 * @param textplain
	 */
	public final void setTextPlain(java.lang.String textplain)
	{
		setTextPlain(getContext(), textplain);
	}

	/**
	 * Set value of TextPlain
	 * @param context
	 * @param textplain
	 */
	public final void setTextPlain(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String textplain)
	{
		getMendixObject().setValue(context, MemberNames.TextPlain.toString(), textplain);
	}

	/**
	 * @return value of TextFormatted
	 */
	public final java.lang.String getTextFormatted()
	{
		return getTextFormatted(getContext());
	}

	/**
	 * @param context
	 * @return value of TextFormatted
	 */
	public final java.lang.String getTextFormatted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TextFormatted.toString());
	}

	/**
	 * Set value of TextFormatted
	 * @param textformatted
	 */
	public final void setTextFormatted(java.lang.String textformatted)
	{
		setTextFormatted(getContext(), textformatted);
	}

	/**
	 * Set value of TextFormatted
	 * @param context
	 * @param textformatted
	 */
	public final void setTextFormatted(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String textformatted)
	{
		getMendixObject().setValue(context, MemberNames.TextFormatted.toString(), textformatted);
	}

	/**
	 * @return value of Source
	 */
	public final java.lang.String getSource()
	{
		return getSource(getContext());
	}

	/**
	 * @param context
	 * @return value of Source
	 */
	public final java.lang.String getSource(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Source.toString());
	}

	/**
	 * Set value of Source
	 * @param source
	 */
	public final void setSource(java.lang.String source)
	{
		setSource(getContext(), source);
	}

	/**
	 * Set value of Source
	 * @param context
	 * @param source
	 */
	public final void setSource(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String source)
	{
		getMendixObject().setValue(context, MemberNames.Source.toString(), source);
	}

	/**
	 * @return value of RetweetCount
	 */
	public final java.lang.Long getRetweetCount()
	{
		return getRetweetCount(getContext());
	}

	/**
	 * @param context
	 * @return value of RetweetCount
	 */
	public final java.lang.Long getRetweetCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.RetweetCount.toString());
	}

	/**
	 * Set value of RetweetCount
	 * @param retweetcount
	 */
	public final void setRetweetCount(java.lang.Long retweetcount)
	{
		setRetweetCount(getContext(), retweetcount);
	}

	/**
	 * Set value of RetweetCount
	 * @param context
	 * @param retweetcount
	 */
	public final void setRetweetCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long retweetcount)
	{
		getMendixObject().setValue(context, MemberNames.RetweetCount.toString(), retweetcount);
	}

	/**
	 * @return value of FavoriteCount
	 */
	public final java.lang.Long getFavoriteCount()
	{
		return getFavoriteCount(getContext());
	}

	/**
	 * @param context
	 * @return value of FavoriteCount
	 */
	public final java.lang.Long getFavoriteCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.FavoriteCount.toString());
	}

	/**
	 * Set value of FavoriteCount
	 * @param favoritecount
	 */
	public final void setFavoriteCount(java.lang.Long favoritecount)
	{
		setFavoriteCount(getContext(), favoritecount);
	}

	/**
	 * Set value of FavoriteCount
	 * @param context
	 * @param favoritecount
	 */
	public final void setFavoriteCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long favoritecount)
	{
		getMendixObject().setValue(context, MemberNames.FavoriteCount.toString(), favoritecount);
	}

	/**
	 * @return value of TweetUser
	 */
	public final twittermodule.proxies.User getTweetUser() throws com.mendix.core.CoreException
	{
		return getTweetUser(getContext());
	}

	/**
	 * @param context
	 * @return value of TweetUser
	 */
	public final twittermodule.proxies.User getTweetUser(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		twittermodule.proxies.User result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TweetUser.toString());
		if (identifier != null)
			result = twittermodule.proxies.User.load(context, identifier);
		return result;
	}

	/**
	 * Set value of TweetUser
	 * @param tweetuser
	 */
	public final void setTweetUser(twittermodule.proxies.User tweetuser)
	{
		setTweetUser(getContext(), tweetuser);
	}

	/**
	 * Set value of TweetUser
	 * @param context
	 * @param tweetuser
	 */
	public final void setTweetUser(com.mendix.systemwideinterfaces.core.IContext context, twittermodule.proxies.User tweetuser)
	{
		if (tweetuser == null)
			getMendixObject().setValue(context, MemberNames.TweetUser.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.TweetUser.toString(), tweetuser.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return tweetMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final twittermodule.proxies.Tweet that = (twittermodule.proxies.Tweet) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TwitterModule.Tweet";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
