// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package twittermodule.proxies;

public class User
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject userMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TwitterModule.User";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		UserId("UserId"),
		Name("Name"),
		ScreenName("ScreenName"),
		ProfileImageURL("ProfileImageURL"),
		ProfileURL("ProfileURL"),
		TweetUser("TwitterModule.TweetUser");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public User(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TwitterModule.User"));
	}

	protected User(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject userMendixObject)
	{
		if (userMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TwitterModule.User", userMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TwitterModule.User");

		this.userMendixObject = userMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'User.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static twittermodule.proxies.User initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return twittermodule.proxies.User.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static twittermodule.proxies.User initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new twittermodule.proxies.User(context, mendixObject);
	}

	public static twittermodule.proxies.User load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return twittermodule.proxies.User.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of UserId
	 */
	public final java.lang.Long getUserId()
	{
		return getUserId(getContext());
	}

	/**
	 * @param context
	 * @return value of UserId
	 */
	public final java.lang.Long getUserId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.UserId.toString());
	}

	/**
	 * Set value of UserId
	 * @param userid
	 */
	public final void setUserId(java.lang.Long userid)
	{
		setUserId(getContext(), userid);
	}

	/**
	 * Set value of UserId
	 * @param context
	 * @param userid
	 */
	public final void setUserId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long userid)
	{
		getMendixObject().setValue(context, MemberNames.UserId.toString(), userid);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of ScreenName
	 */
	public final java.lang.String getScreenName()
	{
		return getScreenName(getContext());
	}

	/**
	 * @param context
	 * @return value of ScreenName
	 */
	public final java.lang.String getScreenName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ScreenName.toString());
	}

	/**
	 * Set value of ScreenName
	 * @param screenname
	 */
	public final void setScreenName(java.lang.String screenname)
	{
		setScreenName(getContext(), screenname);
	}

	/**
	 * Set value of ScreenName
	 * @param context
	 * @param screenname
	 */
	public final void setScreenName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String screenname)
	{
		getMendixObject().setValue(context, MemberNames.ScreenName.toString(), screenname);
	}

	/**
	 * @return value of ProfileImageURL
	 */
	public final java.lang.String getProfileImageURL()
	{
		return getProfileImageURL(getContext());
	}

	/**
	 * @param context
	 * @return value of ProfileImageURL
	 */
	public final java.lang.String getProfileImageURL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProfileImageURL.toString());
	}

	/**
	 * Set value of ProfileImageURL
	 * @param profileimageurl
	 */
	public final void setProfileImageURL(java.lang.String profileimageurl)
	{
		setProfileImageURL(getContext(), profileimageurl);
	}

	/**
	 * Set value of ProfileImageURL
	 * @param context
	 * @param profileimageurl
	 */
	public final void setProfileImageURL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String profileimageurl)
	{
		getMendixObject().setValue(context, MemberNames.ProfileImageURL.toString(), profileimageurl);
	}

	/**
	 * @return value of ProfileURL
	 */
	public final java.lang.String getProfileURL()
	{
		return getProfileURL(getContext());
	}

	/**
	 * @param context
	 * @return value of ProfileURL
	 */
	public final java.lang.String getProfileURL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProfileURL.toString());
	}

	/**
	 * Set value of ProfileURL
	 * @param profileurl
	 */
	public final void setProfileURL(java.lang.String profileurl)
	{
		setProfileURL(getContext(), profileurl);
	}

	/**
	 * Set value of ProfileURL
	 * @param context
	 * @param profileurl
	 */
	public final void setProfileURL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String profileurl)
	{
		getMendixObject().setValue(context, MemberNames.ProfileURL.toString(), profileurl);
	}

	/**
	 * @return value of TweetUser
	 */
	public final twittermodule.proxies.Tweet getTweetUser() throws com.mendix.core.CoreException
	{
		return getTweetUser(getContext());
	}

	/**
	 * @param context
	 * @return value of TweetUser
	 */
	public final twittermodule.proxies.Tweet getTweetUser(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		twittermodule.proxies.Tweet result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TweetUser.toString());
		if (identifier != null)
			result = twittermodule.proxies.Tweet.load(context, identifier);
		return result;
	}

	/**
	 * Set value of TweetUser
	 * @param tweetuser
	 */
	public final void setTweetUser(twittermodule.proxies.Tweet tweetuser)
	{
		setTweetUser(getContext(), tweetuser);
	}

	/**
	 * Set value of TweetUser
	 * @param context
	 * @param tweetuser
	 */
	public final void setTweetUser(com.mendix.systemwideinterfaces.core.IContext context, twittermodule.proxies.Tweet tweetuser)
	{
		if (tweetuser == null)
			getMendixObject().setValue(context, MemberNames.TweetUser.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.TweetUser.toString(), tweetuser.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return userMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final twittermodule.proxies.User that = (twittermodule.proxies.User) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TwitterModule.User";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
